[build]
  command = "yarn build"
  functions = "lambda" #  netlify-lambda reads this
  publish = "public"

[context.production.environment]
  GATSBY_STRIPE_PLAN = "plan_FA1maWmEMVsFUe" # production plan

[context.deploy-preview.environment]
  GATSBY_STRIPE_PLAN = "plan_EbzcEa5yCpjaMM" # test plan

[context.branch-deploy.environment]
  NODE_ENV = "plan_EbzcEa5yCpjaMM"  # test plan
